# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/alena/Documents/color_palette

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/alena/Documents/color_palette

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/alena/Documents/color_palette/CMakeFiles /mnt/c/Users/alena/Documents/color_palette/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/alena/Documents/color_palette/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named palette

# Build rule for target.
palette: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 palette
.PHONY : palette

# fast build rule for target.
palette/fast:
	$(MAKE) -f CMakeFiles/palette.dir/build.make CMakeFiles/palette.dir/build
.PHONY : palette/fast

srcs/bmp.o: srcs/bmp.c.o

.PHONY : srcs/bmp.o

# target to build an object file
srcs/bmp.c.o:
	$(MAKE) -f CMakeFiles/palette.dir/build.make CMakeFiles/palette.dir/srcs/bmp.c.o
.PHONY : srcs/bmp.c.o

srcs/bmp.i: srcs/bmp.c.i

.PHONY : srcs/bmp.i

# target to preprocess a source file
srcs/bmp.c.i:
	$(MAKE) -f CMakeFiles/palette.dir/build.make CMakeFiles/palette.dir/srcs/bmp.c.i
.PHONY : srcs/bmp.c.i

srcs/bmp.s: srcs/bmp.c.s

.PHONY : srcs/bmp.s

# target to generate assembly for a file
srcs/bmp.c.s:
	$(MAKE) -f CMakeFiles/palette.dir/build.make CMakeFiles/palette.dir/srcs/bmp.c.s
.PHONY : srcs/bmp.c.s

srcs/image.o: srcs/image.c.o

.PHONY : srcs/image.o

# target to build an object file
srcs/image.c.o:
	$(MAKE) -f CMakeFiles/palette.dir/build.make CMakeFiles/palette.dir/srcs/image.c.o
.PHONY : srcs/image.c.o

srcs/image.i: srcs/image.c.i

.PHONY : srcs/image.i

# target to preprocess a source file
srcs/image.c.i:
	$(MAKE) -f CMakeFiles/palette.dir/build.make CMakeFiles/palette.dir/srcs/image.c.i
.PHONY : srcs/image.c.i

srcs/image.s: srcs/image.c.s

.PHONY : srcs/image.s

# target to generate assembly for a file
srcs/image.c.s:
	$(MAKE) -f CMakeFiles/palette.dir/build.make CMakeFiles/palette.dir/srcs/image.c.s
.PHONY : srcs/image.c.s

srcs/main.o: srcs/main.c.o

.PHONY : srcs/main.o

# target to build an object file
srcs/main.c.o:
	$(MAKE) -f CMakeFiles/palette.dir/build.make CMakeFiles/palette.dir/srcs/main.c.o
.PHONY : srcs/main.c.o

srcs/main.i: srcs/main.c.i

.PHONY : srcs/main.i

# target to preprocess a source file
srcs/main.c.i:
	$(MAKE) -f CMakeFiles/palette.dir/build.make CMakeFiles/palette.dir/srcs/main.c.i
.PHONY : srcs/main.c.i

srcs/main.s: srcs/main.c.s

.PHONY : srcs/main.s

# target to generate assembly for a file
srcs/main.c.s:
	$(MAKE) -f CMakeFiles/palette.dir/build.make CMakeFiles/palette.dir/srcs/main.c.s
.PHONY : srcs/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... palette"
	@echo "... srcs/bmp.o"
	@echo "... srcs/bmp.i"
	@echo "... srcs/bmp.s"
	@echo "... srcs/image.o"
	@echo "... srcs/image.i"
	@echo "... srcs/image.s"
	@echo "... srcs/main.o"
	@echo "... srcs/main.i"
	@echo "... srcs/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

